Repository beclab/TermiPass, pull requests merged in 2024-07, with the labels that each got.

#68 feat: support integration
  packages/app/package-lock.json
  packages/app/src-capacitor/android/app/build.gradle
  packages/app/src-capacitor/android/app/src/main/AndroidManifest.xml
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/MainActivity.java
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/CustomGooglePlugin.java
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/DropboxAppConfig.kt
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/DropboxPlugin.kt
  packages/app/src-capacitor/capacitor.config.json
  packages/app/src-capacitor/ios/App/App.xcodeproj/project.pbxproj
  packages/app/src-capacitor/ios/App/App/AppDelegate.swift
  packages/app/src-capacitor/ios/App/App/Info.plist
  packages/app/src-capacitor/ios/App/App/Plugins/Dropbox/DropboxAuthPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/Dropbox/DropboxAuthPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/Dropbox/DropboxOauthManager.swift
  packages/app/src-capacitor/ios/App/App/Plugins/GoogleAuthPlugin/GoogleAuthPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/GoogleAuthPlugin/GoogleAuthPlugin.swift
  packages/app/src-capacitor/ios/App/Podfile
  packages/app/src-capacitor/ios/App/Podfile.lock
  packages/app/src/assets/setting/integration/aws.svg
  packages/app/src/assets/setting/integration/dropbox.svg
  packages/app/src/assets/setting/integration/google.svg
  packages/app/src/assets/setting/integration/space.svg
  packages/app/src/components/common/ConfirmButton.vue
  packages/app/src/components/common/TerminusItem.vue
  packages/app/src/components/common/TerminusMobileTitleConfirmView.vue
  packages/app/src/i18n/en-US/index.ts
  packages/app/src/pages/Mobile/integration/IntegrationActionsDialog.vue
  packages/app/src/pages/Mobile/integration/IntegrationAddPage.vue
  packages/app/src/pages/Mobile/integration/IntegrationDetailPage.vue
  packages/app/src/pages/Mobile/integration/IntegrationItem.vue
  packages/app/src/pages/Mobile/integration/IntegrationPage.vue
  packages/app/src/pages/Mobile/integration/aws/AwsAddIntegrationPage.vue
  packages/app/src/pages/Mobile/setting/AccountPage.vue
  packages/app/src/pages/Mobile/setting/IntegrationActionsDialog.vue
  packages/app/src/pages/Mobile/setting/IntegrationAddPage.vue
  packages/app/src/pages/Mobile/setting/IntegrationDetailPage.vue
  packages/app/src/pages/Mobile/setting/IntegrationPage.vue
  packages/app/src/pages/Mobile/setting/SettingIndex.vue
  packages/app/src/pages/Mobile/setting/SpaceManagementPage.vue
  packages/app/src/plugins/dropbox/definitions.ts
  packages/app/src/plugins/dropbox/index.ts
  packages/app/src/plugins/dropbox/web.ts
  packages/app/src/plugins/googleAuth/definitions.ts
  packages/app/src/plugins/googleAuth/index.ts
  packages/app/src/plugins/googleAuth/web.ts
  packages/app/src/router/routes/routes-mobile-common.ts
  packages/app/src/services/abstractions/integration/integrationService.ts
  packages/app/src/services/integration/awss3.ts
  packages/app/src/services/integration/dropbox.ts
  packages/app/src/services/integration/googleDrive.ts
  packages/app/src/services/integration/index.ts
  packages/app/src/services/integration/space.ts
  packages/app/src/stores/integration.ts
Labels: feat

#69 fix: mobile files module request error
  packages/app/src/api/fetch.ts
  packages/app/src/components/common/TerminusDialogBar.vue
  packages/app/src/pages/Mobile/setting/SettingIndex.vue
  packages/app/src/platform/httpProxy.ts
  packages/app/src/services/integration/space.ts
Labels: fix

#71 ci: main delete feat/video
  .github/workflows/update-frontend-files.yml
Labels: ci

#73 fix: data migration
  packages/app/src/pages/Mobile/login/unlock/UnlockBusiness.ts
  packages/app/src/platform/bex/front/platform.ts
  packages/app/src/platform/electron/electronPlatform.ts
  packages/app/src/platform/terminusCommon/terminalCommonPlatform.ts
  packages/app/src/stores/user.ts
  packages/sdk/src/core/user.ts
Labels: fix

#74 fix: scan qrcode bug
  packages/app/package-lock.json
  packages/app/package.json
  packages/app/src-capacitor/ios/App/Podfile.lock
  packages/app/src-capacitor/package.json
  packages/app/src/layouts/TermipassLayout/FilesDrawer.vue
  packages/app/src/platform/terminusCommon/terminalCommonPlatform.ts
Labels: fix

#75 fix: bind custom vc need unlock first
  packages/app/src/pages/Mobile/login/vc/BindCustomerVC.vue
  packages/app/src/platform/homeLayoutCommon.ts
Labels: fix

#78 feat(mobile): support capacitor v6
  packages/app/package-lock.json
  packages/app/package.json
  packages/app/src-capacitor/android/app/capacitor.build.gradle
  packages/app/src-capacitor/android/app/src/main/AndroidManifest.xml
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/MainActivity.java
  packages/app/src-capacitor/android/build.gradle
  packages/app/src-capacitor/android/capacitor.settings.gradle
  packages/app/src-capacitor/android/gradle/wrapper/gradle-wrapper.properties
  packages/app/src-capacitor/android/variables.gradle
  packages/app/src-capacitor/ios/App/App.xcodeproj/project.pbxproj
  packages/app/src-capacitor/ios/App/App/Base.lproj/Main.storyboard
  packages/app/src-capacitor/ios/App/App/Plugins/AppSettings/AppSettingsPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/AppSettings/AppSettingsPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/AutofilliOS/AutofilliOSPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/AutofilliOS/AutofilliOSPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/Dropbox/DropboxAuthPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/Dropbox/DropboxAuthPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/GoogleAuthPlugin/GoogleAuthPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/GoogleAuthPlugin/GoogleAuthPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/HookCapacitorHttp/HookCapacitorHttpPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/HookCapacitorHttp/HookCapacitorHttpPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/ProxyInfo/ProxyInfoPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/StorageiOS/StorageUseriOSPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/StorageiOS/StorageUseriOSPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/StorageiOS/StorageiOSPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/StorageiOS/StorageiOSPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/TwitterLogin/TwitterLoginPlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/TwitterLogin/TwitterLoginPlugin.swift
  packages/app/src-capacitor/ios/App/App/Plugins/VPN/TailScalePlugin.m
  packages/app/src-capacitor/ios/App/App/Plugins/VPN/TailScalePlugin.swift
  packages/app/src-capacitor/ios/App/App/TermipassRootController.swift
  packages/app/src-capacitor/ios/App/Podfile
  packages/app/src-capacitor/ios/App/Podfile.lock
  packages/app/src-capacitor/package-lock.json
  packages/app/src-capacitor/package.json
  packages/app/src/boot/smartEnginEntrance.js
  packages/app/src/platform/capacitor/capacitorPlatform.ts
  packages/app/src/platform/capacitor/iOS/iOSRegisterPlugins.ts
  packages/app/src/plugins/Seafile/definitions.ts
  packages/app/src/plugins/Seafile/index.ts
Labels: feat

#79 fix: Show settings for Vault
  packages/app/src/pages/Files/common-files/FilePreview.vue
  packages/app/src/pages/Web/Settings/IndexList.vue
  packages/app/src/stores/menu.ts
Labels: fix

#77 feat: mobile release with remove integration
  .github/workflows/update-android.yml
  .github/workflows/update-ios.yml
  packages/app/package-lock.json
  packages/app/package.json
  packages/app/quasar.config.js
  packages/app/src-capacitor/android/capacitor.settings.gradle
  packages/app/src-capacitor/ios/App/App/App.entitlements
  packages/app/src-capacitor/ios/App/App/AppRelease.entitlements
  packages/app/src-capacitor/ios/App/App/Info.plist
  packages/app/src-capacitor/ios/App/Podfile
  packages/app/src-capacitor/ios/App/Podfile.lock
  packages/app/src-capacitor/ios/App/shell/build_config.txt
  packages/app/src-capacitor/package-lock.json
  packages/app/src-capacitor/package.json
  packages/app/src/components/common/TerminusEdit.vue
  packages/app/src/did/did-key.js
  packages/app/src/pages/Desktop/unlock/DesktopUnlockLayout.vue
  packages/app/src/pages/Desktop/unlock/UnlockPage.vue
  packages/app/src/pages/Items/ItemList.vue
  packages/app/src/pages/Mobile/connect/ConnectLoading.vue
  packages/app/src/pages/Mobile/connect/activate/ActivateTerminus.vue
  packages/app/src/pages/Mobile/connect/activate/ResetPassword.vue
  packages/app/src/pages/Mobile/integration/IntegrationItem.vue
  packages/app/src/pages/Mobile/setting/SettingIndex.vue
  packages/app/src/pages/Mobile/vault/ItemIndex.vue
  packages/app/src/plugins/Seafile/web.ts
Labels: feat

#80 feat: Add Drive Route in Files Route
  docker/files/nginx.conf
Labels: feat

#83 fix: mobile add video
  packages/app/src/api/drive/data.ts
  packages/app/src/api/drive/filesFormat.ts
  packages/app/src/components/files/ListingItem.vue
  packages/app/src/pages/Files/common-files/FileVideoPreview.vue
  packages/app/src/pages/Mobile/file/ListingItem.vue
  packages/app/src/utils/appdata.js
Labels: fix

#84 fix: video modal-dialog-content
  packages/app/src/api/drive/data.ts
  packages/app/src/components/files/files/FileOperationItem.vue
  packages/app/src/css/video/city.video.css
Labels: fix

#85 feat: update nginx and check Application
  .github/workflows/update-frontend-files.yml
  docker/files/nginx.conf
  packages/app/src/api/common/common.ts
  packages/app/src/api/drive/data.ts
  packages/app/src/api/drive/filesFormat.ts
  packages/app/src/api/fetch.ts
  packages/app/src/pages/Files/common-files/FilesFooter.vue
  packages/app/src/pages/Files/common-files/FilesHeader.vue
  packages/app/src/pages/Files/common-files/ListingFiles.vue
  packages/app/src/stores/files-menu.ts
  packages/app/src/stores/files.ts
Labels: feat

#88 fix: hot-fix nginx bug
  docker/files/nginx.conf
Labels: fix
