Repository beclab/TermiPass, pull requests merged in 2024-05, with the labels that each got.

#11 fix: Vault Orgs update data and Files operate
  packages/app/quasar.config.js
  packages/app/src/components/files/prompts/InfoDialog.vue
  packages/app/src/components/files/prompts/ShareDialog.vue
  packages/app/src/globals.ts
  packages/app/src/layouts/TermipassLayout/VaultsMenu.vue
  packages/app/src/pages/Files/common-files/FilePreview.vue
  packages/app/src/pages/Items/ItemsDrawer.vue
  packages/app/src/pages/Web/Orgs/dashboard/OrgDashboardIndex.vue
  packages/app/src/pages/Web/Orgs/invites/OrgInvitesList.vue
  packages/app/src/pages/Web/Orgs/invites/OrgInvitesView.vue
  packages/app/src/pages/Web/Orgs/members/OrgMemberItem.vue
  packages/app/src/pages/Web/Orgs/members/OrgMembersList.vue
  packages/app/src/pages/Web/Orgs/members/OrgMembersView.vue
  packages/app/src/pages/Web/Orgs/vaults/OrgVaultsList.vue
  packages/app/src/pages/Web/Settings/SecurityPage.vue
  packages/app/src/stores/menu.ts
  packages/app/src/utils/bus.ts
Labels: bug

#14 fix: Fix sync issues with Orgs
  package.json
  packages/app/src/components/files/ListingItem.vue
  packages/app/src/components/files/prompts/InfoDialog.vue
  packages/app/src/pages/Web/Orgs/invites/OrgInvitesList.vue
  packages/app/src/pages/Web/Orgs/invites/OrgInvitesView.vue
  packages/app/src/pages/Web/Orgs/members/OrgMemberItem.vue
  packages/app/src/pages/Web/Orgs/members/OrgMembersList.vue
  packages/app/src/pages/Web/Orgs/members/OrgMembersView.vue
  packages/app/src/pages/Web/Orgs/vaults/OrgVaultsList.vue
  packages/app/src/pages/Web/Orgs/vaults/OrgVaultsView.vue
  packages/app/src/stores/menu.ts
  packages/app/src/stores/user.ts
  packages/sdk/src/core/app.ts
Labels: bug

#15 fix: fix orgs ui issue
  packages/app/src/api/files.js
  packages/app/src/api/utils.js
  packages/app/src/globals.ts
  packages/app/src/pages/Web/Orgs/OrgIndexPage.vue
  packages/app/src/pages/Web/Orgs/groups/OrgGroupItem.vue
  packages/app/src/pages/Web/Orgs/groups/OrgGroupsIndex.vue
  packages/app/src/pages/Web/Orgs/groups/OrgGroupsView.vue
  packages/app/src/pages/Web/Orgs/invites/OrgInvitesIndex.vue
  packages/app/src/pages/Web/Orgs/invites/OrgInvitesList.vue
  packages/app/src/pages/Web/Orgs/invites/OrgInvitesView.vue
  packages/app/src/pages/Web/Orgs/members/OrgMembersIndex.vue
  packages/app/src/pages/Web/Orgs/members/OrgMembersList.vue
  packages/app/src/pages/Web/Orgs/members/OrgMembersView.vue
  packages/app/src/pages/Web/Orgs/vaults/DeleteVault.vue
  packages/app/src/pages/Web/Orgs/vaults/OrgVaultsIndex.vue
  packages/app/src/pages/Web/Orgs/vaults/OrgVaultsList.vue
  packages/app/src/pages/Web/Orgs/vaults/OrgVaultsView.vue
  packages/app/src/pages/Web/Security/IndexPage.vue
  packages/app/src/stores/menu.ts
  packages/sdk/src/core/app.ts
Labels: bug

#24 fix: Update sync icons in the files menu
  packages/app/src/api/sync.js
  packages/app/src/i18n/en-US/index.ts
  packages/app/src/layouts/TermipassLayout/FilesDrawer.vue
  packages/app/src/stores/files-menu.ts
Labels: bug

#26 fix: upload uploadModal
  packages/app/src/api/files.js
  packages/app/src/api/utils.js
  packages/app/src/components/files/UploadModal.vue
  packages/app/src/components/files/UploadSyncModal.vue
  packages/app/src/css/listing.css
  packages/app/src/layouts/TermipassLayout/FilesDrawer.vue
  packages/app/src/pages/Files/common-files/FileUploader.vue
  packages/app/src/pages/Files/common-files/ListingFiles.vue
  packages/app/src/stores/data.ts
Labels: bug

#36 feat: update docker and nginx file path
  .github/workflows/update-admin.yml
  .github/workflows/update-frontend-files.yml
  .github/workflows/update-frontend.yml
  .github/workflows/update-notification.yml
  .github/workflows/update-server.yml
  docker/admin/dockerfile
  docker/files/dockerfile
  docker/files/nginx.conf
  docker/notification/dockerfile
  docker/server/dockerfile
  docker/vault/dockerfile
  docker/vault/nginx.conf
Labels: feat

#38 fix: remove local broadcast and fix autofill framework call autofill list multiple times
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/MainActivity.java
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/AccessibilityPlugin.kt
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/AndroidUniversalPlugin.kt
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/AutofillFrameworkPlugin.kt
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/IntentReceiver.kt
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/OnHandleIntentListener.kt
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/plugins/OnSendIntentDataListener.kt
Labels: fix

#39 fix: import account without bind vc enter active page
  packages/app/src/components/common/TerminusAccountItem.vue
  packages/app/src/pages/Mobile/connect/activate/ScanPage.vue
  packages/app/src/pages/Mobile/login/account/ImportUserBusiness.ts
  packages/app/src/platform/terminusCommon/terminalCommonPlatform.ts
Labels: fix

#40 fix: mobile use package.json version error
  packages/app/package-lock.json
  packages/app/quasar.config.js
  packages/app/src-capacitor/android/app/build.gradle
  packages/app/src-capacitor/ios/App/shell/config.sh
  packages/app/src/pages/Mobile/connect/activate/ResetPassword.vue
Labels: fix

#41 fix: using IntentSender to send an Intent and start an activity in the autofill framework after Android P (API level 28)
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/autofill/AutofillHelper.kt
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/autofill/VaultAutoFillService.kt
  packages/app/src-capacitor/android/app/src/main/java/com/terminus/planeta/utils/Constants.kt
Labels: fix

#42 fix: update nginx config
  docker/files/nginx.conf
  docker/vault/nginx.conf
Labels: fix

#43 fix: update timeout for request
  packages/app/src/api/files.js
  packages/app/src/api/utils.js
Labels: fix

#47 fix: update nginx timeout
  .github/workflows/pr-conventional-commit-validation.yml
  docker/vault/nginx.conf
  packages/app/src/api/seahub.js
  packages/app/src/components/files/files/OperateAction.ts
  packages/app/src/components/files/files/OperateMenu.vue
  packages/app/src/pages/Files/FilesPage.vue
Labels: fix

#48 fix(mobile): active wizard page get terminus info
  packages/app/package.json
  packages/app/src-capacitor/ios/App/App.xcodeproj/project.pbxproj
  packages/app/src-capacitor/ios/App/App/Info.plist
  packages/app/src-capacitor/package.json
  packages/app/src/pages/Desktop/SettingsPage/Settings.vue
  packages/app/src/pages/Mobile/connect/activate/ActivateWizard.vue
Labels: fix
